"""Maps Whisper's ISO-639-1-ish language codes to NLLB-200's FLORES-200 codes."""

WHISPER_TO_NLLB = {
    "en": "eng_Latn",
    "es": "spa_Latn",
    "pt": "por_Latn",
    "fr": "fra_Latn",
    "de": "deu_Latn",
    "it": "ita_Latn",
    "ru": "rus_Cyrl",
    "ja": "jpn_Jpan",
    "ko": "kor_Hang",
    "zh": "zho_Hans",
    "ar": "arb_Arab",
    "tr": "tur_Latn",
    "pl": "pol_Latn",
    "nl": "nld_Latn",
    "sv": "swe_Latn",
    "no": "nob_Latn",
    "da": "dan_Latn",
    "fi": "fin_Latn",
    "cs": "ces_Latn",
    "el": "ell_Grek",
    "he": "heb_Hebr",
    "hi": "hin_Deva",
    "id": "ind_Latn",
    "vi": "vie_Latn",
    "th": "tha_Thai",
    "uk": "ukr_Cyrl",
    "ro": "ron_Latn",
    "hu": "hun_Latn",
    "bg": "bul_Cyrl",
    "hr": "hrv_Latn",
    "sk": "slk_Latn",
    "sl": "slv_Latn",
    "et": "est_Latn",
    "lv": "lvs_Latn",
    "lt": "lit_Latn",
    "fa": "pes_Arab",
    "ur": "urd_Arab",
    "bn": "ben_Beng",
    "ta": "tam_Taml",
    "te": "tel_Telu",
    "ms": "zsm_Latn",
    "tl": "tgl_Latn",
    "sw": "swh_Latn",
    "af": "afr_Latn",
    "ca": "cat_Latn",
    "gl": "glg_Latn",
    "eu": "eus_Latn",
    "is": "isl_Latn",
    "ga": "gle_Latn",
    "cy": "cym_Latn",
    "sq": "als_Latn",
    "mk": "mkd_Cyrl",
    "sr": "srp_Cyrl",
    "bs": "bos_Latn",
    "mn": "khk_Cyrl",
    "ka": "kat_Geor",
    "hy": "hye_Armn",
    "az": "azj_Latn",
    "kk": "kaz_Cyrl",
    "uz": "uzn_Latn",
    "ne": "npi_Deva",
    "si": "sin_Sinh",
    "km": "khm_Khmr",
    "lo": "lao_Laoo",
    "my": "mya_Mymr",
    "am": "amh_Ethi",
    "so": "som_Latn",
    "zu": "zul_Latn",
    "xh": "xho_Latn",
    "yo": "yor_Latn",
    "ig": "ibo_Latn",
    "ha": "hau_Latn",
    "pa": "pan_Guru",
    "gu": "guj_Gujr",
    "mr": "mar_Deva",
    "kn": "kan_Knda",
    "ml": "mal_Mlym",
    "sd": "snd_Arab",
    "ps": "pbt_Arab",
    "ku": "kmr_Latn",
    "lb": "ltz_Latn",
    "mt": "mlt_Latn",
    "be": "bel_Cyrl",
    "jw": "jav_Latn",
}

ENGLISH_NLLB = "eng_Latn"


def to_nllb(whisper_lang: str) -> str:
    return WHISPER_TO_NLLB.get(whisper_lang, ENGLISH_NLLB)
